siteStream:
  id: site-stream
  entityId: turtlehead-tacos-demo-site
  fields:
    - name
    - logo
    - c_header
    - c_footer
    - instagramHandle
    - twitterHandle
  localization:
    locales:
      - en
